# Generated by Django 6.0.7 on 2026-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Analysis', 'verbose_name_plural': 'AI Analyses'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['interview_date'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='match_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='important_technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='interview_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='job_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='required_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('online', 'Online'), ('phone', 'Phone'), ('onsite', 'On-site'), ('technical', 'Technical'), ('hr', 'HR'), ('other', 'Other')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
